version: "3.8"

services:
  app:
    build:
      context: .
      target: runtime
    container_name: node_app
    ports:
      - "5173:5173"
    volumes:
      - ./my-data:/app/data
    environment:
      - PORT=5173
      - HOST=0.0.0.0